Position correction
ptycho/ptypy pull request #209
Opened 2019-05-14 10:24 UTC by daurer

This is an implementation of a position correction algorithm as described in:

>  A.M. Maiden, M.J. Humphry, M.C. Sarahan, B. Kraus, J.M. Rodenburg,
>         An annealing algorithm to correct positioning errors in ptychography,
>         Ultramicroscopy, Volume 120, 2012, Pages 64-72

It has originally been implemented by @wfeschen, the full story behind this implementation is described in issue #146 

I have briefly tested the performance of this algorithm with DM (```ptypy/templates/position_correction.py```) but certainly more testing (e.g. ML) and other changes (e.g. to make things compatible with the general ptypy code philosophy) is required.

2019-05-15 04:21 UTC, daurer commented
Added lasted updates from @wfeschen, including an evaluation script for the corrected positions.

2019-05-15 05:39 UTC, bjoernenders reviewed
Hi Benedikt.
I made only a few comments. Am I correct in assuming that you added the parameters to BaseEngine to make the refinement available in both DM_pos_corr and ML_pos_corr ? If so I suggest subclassing from BaseEngine to PosRefEngine and using that engine as base for the two above. Otherwise the parameters for position refinement appear for all other engines breaking backward compatibility.

2019-05-15 05:39 UTC, bjoernenders commented on ptypy/engines/posref.py
> +            if ob_view_temp.data.shape[0] != self.shape[0] or ob_view_temp.data.shape[1] != self.shape[1]:
maybe use np.allclose() here

2019-05-15 05:39 UTC, bjoernenders commented on ptypy/engines/posref.py
> +                # if the data of the view has the wrong shape, zero-pad the data
should we not one-pad the data

2019-05-15 05:39 UTC, bjoernenders commented on ptypy/engines/posref.py
> +                ymin = self.engine.ob.storages.values()[0].grids()[0][0, 0, 0]
I would maybe create reference to the object storage like `ob = di_view.pod.ob_view.storage` at the beginning of the function call ot in this if statement

2019-05-15 05:39 UTC, bjoernenders commented on ptypy/engines/base.py
> +    [posref_start]
We should better use non-flat parameters here. `[posref]` is a group and  `[posref.active]`and then `[posref.start]`

2019-05-15 06:13 UTC, daurer commented
Hi Bjoern,
thanks for your comments. ```DM_pos_corr``` and ```ML_pos_corr``` are actually leftovers from the initial implementation by @wfeschen. I made the changes to the BaseEngine to make the position correction work with the normal ```DM``` engine. This is because I wanted to use other new features that I have implemented in DM (e.g. resample). This touches on the questions raised in #200. 

Unfortunately, I currently have no time to work on this PR, but I hope that @aaron-parsons (maybe with help from @wfeschen) can take over from here and make this position correction idea into a proper ptypy extension.

2019-05-15 11:50 UTC, aaron-parsons commented
Hi all,thanks for all the work/comments. I'll be following this up on Friday since we need it on a couple of beamlines.

2019-05-15 12:12 UTC, aaron-parsons commented
Also, yes I agree with Bjoern with the PosRefineEngine (or similar).That's essentially what the position refine class is doing here, but passing the engine through rather than extending it. It should be pretty simple for me to do this.

2019-05-15 13:01 UTC, aaron-parsons commented on ptypy/engines/posref.py
> +        self.save_pos()
Is there a reason to save the positions here? Now that we dump out the positions at the end anyway #206 I'm thinking not.

2019-05-15 13:05 UTC, aaron-parsons commented on templates/position_evaluation.py
> +    plt.show()
Update this script to show it working for the output .ptyr

2019-05-15 13:06 UTC, aaron-parsons commented on templates/position_refinement.py
> +
We have a similar example for the OPR branch. I wonder if it makes sense just to add it as an option for the moonflower scan.

2019-05-17 10:10 UTC, aaron-parsons commented on ptypy/engines/posref.py
> +class PositionRefine(object):
I think we can split this up a bit. I think PositionRefine should do the calculation, but the iteration through the views should be done in the PositionRefinementEngine class. We can also allocate temp_ob in the engine initialize method then too.

2019-05-17 15:15 UTC, aaron-parsons commented on ptypy/engines/base.py
> +    [posref_start]
I have done this, but #191 is causing issues separate to this PR.

2019-05-17 15:19 UTC, aaron-parsons commented on ptypy/engines/posref.py
> +                # if the data of the view has the wrong shape, zero-pad the data
Actually no padding is done here.

2019-05-17 15:20 UTC, aaron-parsons commented on ptypy/engines/posref.py
> +            if ob_view_temp.data.shape[0] != self.shape[0] or ob_view_temp.data.shape[1] != self.shape[1]:
Yes. I have now done this.

2019-05-17 15:20 UTC, aaron-parsons commented
Not sure why the CI is failing, the test on it's own passes. @bjoernenders @pierrethibault are you happy with this at the moment?

If I fix the CI I am thinking to just merge this. Once my users start working with it, more bugs might become apparent.

One thing I noticed is that I still didn't do #191 which means that it is hard to turn off unless the start and stop are None. Once this one is merged, I'll look at #191

2019-05-17 20:52 UTC, pierrethibault commented on ptypy/engines/base.py
> +    [position_refinement.cycle]
We have used "interval" for this concept in other places in the code...

2019-05-17 20:52 UTC, pierrethibault commented on ptypy/engines/posref.py
> +    def __init__(self, position_refinement_parameters, initial_positions, shape, temp_ob):
Definitely need a docstring here.

2019-05-17 20:52 UTC, pierrethibault commented on ptypy/engines/posref.py
> +        Calculates the fourier error based on a given diffraction and ohject.
```suggestion
        Calculates the fourier error based on a given diffraction and object.
```

2019-05-17 20:52 UTC, pierrethibault commented on ptypy/engines/base.py
> +
```suggestion

    def __init__(def __init__(self, ptycho_parent, pars=None):
        """
        Base engine for position refinement.
        """
        super(PositionCorrectionEngine, self).__init__(ptycho_parent, pars)

        self.ptycho.citations.add_article(
            title='An annealing algorithm to correct positioning errors in ptychography',
            author='Maiden et al.',
            journal='Ultramicroscopy',
            volume=120,
            year=2012,
            page=64,
            doi='10.1016/j.ultramic.2012.06.001',
            comment='Position Refinement using annealing algorithm',
        )

```

2019-05-17 23:35 UTC, bjoernenders commented on ptypy/engines/base.py
> +
We should only add the citation if the position correction has been switched on.

2019-05-18 12:47 UTC, pierrethibault commented on ptypy/engines/base.py
> +
Good point. Ok, let'sl put it somewhere else.

2019-05-18 12:57 UTC, pierrethibault commented on ptypy/engines/posref.py
> +    def reset_access_rule(self):
A docstring here would be good as well.

2019-05-18 21:15 UTC, pierrethibault commented on ptypy/engines/posref.py
> +                # if the data of the view has the wrong shape, zero-pad the data
... actually there is an implicit padding done in line 166, since `new_obj` is initialised as `zeros`. In general I must say I feel that this part of the code is a bit fragile. I wish this type of stuff was folded into the `Storage` or `View` class. Maybe `View.get_data(pad=True)` could return exactly what is computed here on line 166?

Another kind of reasonable approach might be to add the possibility of having extra "safe" padding in a Storage. By padding safely the object storage by the maximum allowed shift, we would know that all views would match, and no test would have to be done at this step. Once all positions are updated we only need to update the safe padding to maintain it. Is the memory cost too high?

2019-05-19 13:10 UTC, pierrethibault commented on ptypy/engines/posref.py
> +                # if the data of the view has the wrong shape, zero-pad the data
I implemented extra padding (branch extrapadding). I think that could be an elegant way of working with this. @bjoernenders @aaron-parsons @daurer @wfeschen opinion?

2019-05-19 13:59 UTC, bjoernenders commented on ptypy/engines/posref.py
> +                # if the data of the view has the wrong shape, zero-pad the data
Yes, good idea, I would have put it at the same location. I don't think though that you should need the padding in `__getitem__` and `__setitem__` ... Shouldn't that be automatically resolved by the views taking on higher and lower values for dlow and dhigh respectively after reformat?

2019-05-19 14:06 UTC, bjoernenders commented on ptypy/engines/posref.py
> +                # if the data of the view has the wrong shape, zero-pad the data
What I want to say is that I would have expected it to just work with the misfit correction in line 658

2019-05-20 08:15 UTC, aaron-parsons commented on ptypy/engines/base.py
> +
Just added this in the appropriate place.

2019-05-20 12:56 UTC, aaron-parsons commented on ptypy/engines/base.py
> +                storage.padding = int(np.round(self.position_refinement.max_shift_dist + 1))
Debugging here shows that the shape is indeed increased.

2019-05-20 12:57 UTC, aaron-parsons commented on ptypy/engines/posref.py
> +                print("I went in here tempshape:%s, self.shape:%s, dx:%s, xy:%s, maxdist:%s" % (ob_view_temp.data.shape, self.shape, delta_x, delta_y, self.max_shift_dist))
But here the shapes are still wrong. I think that this could be because we pad on the -ve side, do we update the coordinates of the views to be increased by the pad size?

2019-05-20 15:02 UTC, aaron-parsons commented on ptypy/engines/base.py
> +                storage.padding = int(np.round(self.position_refinement.max_shift_dist + 1))
Pierre pointed out that the max_distance is in real units, not pixels so this is now fixed.

2019-05-20 16:02 UTC, aaron-parsons commented on ptypy/engines/posref.py
> +        self.ar.storageID = self.temp_ob.storages.values()[0].ID # this bit worries me. Shouldn't it get the ID from the di_view?
Should we be iterating over the object storages?

2019-05-20 16:43 UTC, aaron-parsons commented on ptypy/engines/posref.py
> +        self.ar.storageID = self.temp_ob.storages.values()[0].ID # this bit worries me. Shouldn't it get the ID from the di_view?
I think the answer is no because it's always that first point of interaction that we care about.

2019-05-20 22:10 UTC, pierrethibault approved these changes
Happy to merge.

2019-05-20 22:48 UTC, bjoernenders requested changes

2019-05-20 22:48 UTC, bjoernenders commented on ptypy/engines/posref.py
> +        ob_view_temp = View(self.temp_ob, accessrule=self.ar)
These views need to be cleaned up. I could envision they will grow to unmanageble numbers.

2019-05-20 22:48 UTC, bjoernenders commented on ptypy/engines/posref.py
> +            ob_view_temp = View(self.temp_ob, accessrule=self.ar)
Same here. view_temp is kept forever.

2019-05-20 22:55 UTC, bjoernenders commented on ptypy/engines/posref.py
> +        :param di_view: View to the diffraction pattern of the given position.
Numpy docstrings everywhere please.

2019-05-21 06:39 UTC, bjoernenders commented on ptypy/engines/posref.py
> +        ob_view_temp = View(self.temp_ob, accessrule=self.ar)
Actually let me take care of this. I need to work on the View in faster_views branch anyway

2019-05-21 09:56 UTC, aaron-parsons commented on ptypy/engines/posref.py
> +        ob_view_temp = View(self.temp_ob, accessrule=self.ar)
I'll answer these in a post at the end

2019-05-21 09:56 UTC, aaron-parsons commented on ptypy/engines/posref.py
> +            ob_view_temp = View(self.temp_ob, accessrule=self.ar)
I'll answer these in a post at the end

2019-05-21 09:56 UTC, aaron-parsons commented on ptypy/engines/posref.py
> +        :param di_view: View to the diffraction pattern of the given position.
Done

2019-05-21 10:06 UTC, aaron-parsons commented
Right. I think this is ready to go now.

For the question about tidying up the views. Bjoern and I talked about this. What we should really do to encapsulate the behaviour of the .copy() process is copy and then immediately set container.original to be itself, removing the link to the parent object. Any new views are then created only on the new copied instance and not on the parent.

The problem with this is that, from the Container docs:
    _In order to reduce the number of :any:`View` instances, Container copies
    do not hold views and use instead the Views held by the original container_

This means that after setting container.original to itself you would then have to copy all the views to the new container before doing anything else. **This** seems to me to be a bad idea and would definitely impact performance.

Instead what I have implemented is that at the end of each iteration we delete our container copy and create a fresh copy each time. If the views are somehow kept in memory they will be overwritten by the next iteration anyway.

I think that this needs to be looked at more fully in a separate package of work, which is what Bjoern is doing in #212, and what I'll also be looking at as part of our acceleration upgrades next month. As our beamlines start to use this feature I will certainly be able to spend some more time looking at this, but first they have to get the feature.

Hope that makes sense.

2019-05-21 11:53 UTC, aaron-parsons commented
Ok now this is an issue for me. When running in MPI mode across 2 nodes with 40 cores each, ON the second iteration of position correction I get the following error.

Iteration #21 of DM :: Time 2.45
Errors :: Fourier 4.35e+03, Photons 5.31e-02, Exit 7.84e-02
Smoothing object, average cfact is 0.00
*** Error in `python': double free or corruption (!prev): 0x000055cea39e72c0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81489)[0x2aea7eb66489]
/dls_sw/apps/openmpi/3.0.0-pty/rhel7/x86_64/lib/libmpi.so.40(ompi_coll_base_allreduce_intra_ring+0x180)[0x2aea89d9a3a0]
/dls_sw/apps/openmpi/3.0.0-pty/rhel7/x86_64/lib/libmpi.so.40(PMPI_Allreduce+0x18b)[0x2aea89d5fd5b]
/dls_sw/apps/ptypy/temporary_environment_rhel7/miniconda/envs/full_dependencies/lib/python2.7/site-packages/mpi4py/MPI.so(+0xdce90)[0x2aea89c57e90]
/dls_sw/apps/ptypy/temporary_environment_rhel7/miniconda/envs/full_dependencies/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x7d14)[0x2aea7e0a4ea4]
/dls_sw/apps/ptypy/temporary_environment_rhel7/miniconda/envs/full_dependencies/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9)[0x2aea7e0a66c9]
/dls_sw/apps/ptypy/temporary_environment_rhel7/miniconda/envs/full_dependencies/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6a08)[0x2aea7e0a3b98]
/dls_sw/apps/ptypy/temporary_environment_rhel7/miniconda/envs/full_dependencies/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x7fee)[0x2aea7e0a517e]
/dls_sw/apps/ptypy/temporary_environment_rhel7/miniconda/envs/full_dependencies/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x7fee)[0x2aea7e0a517e]


I have to go now, but any hints are greatly appreciated.

2019-05-21 18:52 UTC, aaron-parsons commented
Ok, by moving log statements backwards in the code, I have identified that this happens in the             parallel.allreduce(s.data) in the object update, the iteration after a position refinement has happened.

Adding some more logging and it's now obvious what happens. Across 10 cores on a single node I get:

INSPECT s.data.shape: (1, 446, 442) , s.data.dtype:complex64, rank:9
INSPECT s.data.shape: (1, 444, 440) , s.data.dtype:complex64, rank:1
INSPECT s.data.shape: (1, 444, 440) , s.data.dtype:complex64, rank:4
INSPECT s.data.shape: (1, 444, 440) , s.data.dtype:complex64, rank:8
INSPECT s.data.shape: (1, 444, 440) , s.data.dtype:complex64, rank:3
INSPECT s.data.shape: (1, 444, 440) , s.data.dtype:complex64, rank:2
INSPECT s.data.shape: (1, 444, 440) , s.data.dtype:complex64, rank:5
INSPECT s.data.shape: (1, 444, 440) , s.data.dtype:complex64, rank:6
INSPECT s.data.shape: (1, 444, 440) , s.data.dtype:complex64, rank:7

So the shape of one of the object storages is wrong. It couldn't just say that I guess....

I think the issue is that I haven't synced the new positions across all cores before doing the ob.reformat. And in the position update I only work with the active diffraction views. This means that each process is getting a different set of co-ordinates to reformat to.
i.e. we set di_view.pod.ob_view.coord, but only for the di_views that are active in each process.

This was mitigated in the original implementation since the positions were stored in one big array that was reduced.

Have to go now again. Tomorrow it shall be fixed.

2019-05-22 03:56 UTC, bjoernenders commented
Hey Aaron.
 I uploaded a fix for your mpi problem. Now hopefully, your storages stay synchronized. This fix is also needed for future strong(er) scaling. There might still be issues with this high turnaround of Container copies. I'm also fine with using container copies. Also, `.reformat()` on the copied container does not considers those views you created on it, but only those in the `original`. Just FYI, I hope you don't need that.

But I don't quite understand, why there needs to be an object copy at all and new views, if you can just let the actual `ob_view` wander around. Also, once the overlap breaks, the annealing procedure breaks, cause the algorithm can have the object fit locally perfect with the data, so they cannot really go far, can they? We could also write an additional method for storage, that bounces views back into its data as a safeguard. Stuff to think about, if this procedure needs performance tweaks in the future.

2019-05-22 10:36 UTC, aaron-parsons commented
thanks Bjoern. This is still not quite there. When I run this with 10 cores not I get:

  File "/home/clb02321/PycharmProjects/position_correction/build/lib/ptypy/engines/utils.py", line 125, in basic_fourier_update
    LL += u.abs2(pod.fw(pod.probe * pod.object))
ValueError: operands could not be broadcast together with shapes (128,128) (128,0) 
    LL += u.abs2(pod.fw(pod.probe * pod.object))
ValueError: operands could not be broadcast together with shapes (128,128) (128,127) 

So I guess the sizes are wrong... I'll take a look.

2019-05-22 15:11 UTC, aaron-parsons commented
This was a problem at my end. We can merge now I think. Thanks everyone.
I'll leave this for @bjoernenders to look at, but otherwise will merge tomorrow morning UK time.

2019-05-23 11:24 UTC, aaron-parsons commented
Ok I am going to merge this now. Any feedback is appreciated via the issues. Thanks @wfeschen @daurer @bjoernenders @pierrethibault

2019-05-23 11:25 UTC, merged