Nanomax classes to match new python3 master
ptycho/ptypy pull request #238
Opened 2019-11-01 09:50 UTC by alexbjorling

Not sure what the release schedule for 0.4 is, but if this could fit in before release, that would be splendid.

2019-11-11 21:50 UTC, bjoernenders approved these changes
I had a quick look and I only found the repeated use of "print" as something that you might to change to "logger.info" etc. Otherwise, PtyScan classes are the responsibility of the beamlines. So I agree to merge. But it will probably be in the rolling master now.

2019-11-11 21:50 UTC, bjoernenders commented on ptypy/experiment/nanomax_streaming.py
> +        print('-------------------------------------')
Consider using the logging functionality of ptypy instead of print. Print shoudl be used for debugging.

2019-11-12 08:04 UTC, alexbjorling commented on ptypy/experiment/nanomax_streaming.py
> +        print('-------------------------------------')
Busted! You're right, I should use the logger.

2020-07-11 11:19 UTC, daurer commented
Was looking through the open PRs and this one looks kind of ready to be merged. @alexbjorling Do you want this merged into master? Only recommendation would be to replace print statements with the logger (as suggested above).

2020-09-14 12:59 UTC, alexbjorling commented
Sorry @daurer I missed this update. Hang on, I'll just put in another tiny feature first and then ask to merge.

2020-09-14 13:21 UTC, alexbjorling commented
Ok! Please merge and close this request. @daurer @bjoernenders

2020-09-14 17:44 UTC, bjoernenders requested changes

2020-09-14 17:44 UTC, bjoernenders commented on ptypy/experiment/__init__.py.orig
> +>>>>>>> master
Here is a merge conflict.

2020-09-14 17:46 UTC, bjoernenders commented on ptypy/experiment/__init__.py.orig
> +>>>>>>> master
I actually don't understand this file __init__.py.orig. Did you commit a backup file by accident?

2020-09-14 17:58 UTC, alexbjorling commented on ptypy/experiment/__init__.py.orig
> +>>>>>>> master
yep sorry, must have backed it up when resolving some earlier conflict

2020-09-14 18:51 UTC, bjoernenders approved these changes

2020-09-14 18:57 UTC, bjoernenders commented
I would do a squash merge, since this a topic/side branch. Is that ok with you?

2020-09-14 20:08 UTC, alexbjorling commented
> I would do a squash merge, since this a topic/side branch. Is that ok with you?

of course!

2020-09-14 20:36 UTC, merged

2020-09-14 20:39 UTC, bjoernenders commented
Merged and topic branch deleted.