Gpu hackathon: crop pad
ptycho/ptypy pull request #303
Opened 2021-03-09 16:49 UTC by xcelerit-team

This GPU implementation makes all tests pass for crop/pad. However, I feel the tests should be extended to cover the following corner cases / special cases:
- higher dimensionality, like 5D or 6D
- larger arrays, possibly random, where A is not just filled with zeros initially (also to use multiple thread blocks on the GPU and make sure that behaves fine)

We should also add a performance test (skipped by default) with something large, to run a profile and make sure the implementation is efficient.

Note that this kernel is the full fill3D, not just the simplified version - tests for that case should also be added to verify if that's working fine.

2021-03-09 16:56 UTC, bjoernenders commented
You're right, these test needs to be expanded to larger sizes for unity testing. Didn't make to much sense for the references though.

2021-03-09 21:23 UTC, bjoernenders requested changes

2021-03-09 21:23 UTC, bjoernenders commented on ptypy/accelerate/cuda_pycuda/array_utils.py
> +    def fill3D(self, A, B, offset=[0, 0, 0]):
I didn't see this before. There is no need to make this part of a "Kernel", or is there? It doesn't require a state or needs to allocate resources. We should keep those as simple functions, just like the blueprint in `base`

2021-03-09 21:23 UTC, bjoernenders commented on ptypy/accelerate/cuda_pycuda/kernels.py
> +from .array_utils import ArrayUtilsKernel
It should not be a Kernel

2021-03-09 21:32 UTC, xcelerit-team commented on ptypy/accelerate/cuda_pycuda/array_utils.py
> +    def fill3D(self, A, B, offset=[0, 0, 0]):
The state they keep is the compiled kernel code. Without the class, you’d need to recompile on every run.

2021-03-09 21:39 UTC, daurer commented on ptypy/accelerate/cuda_pycuda/array_utils.py
> +    def fill3D(self, A, B, offset=[0, 0, 0]):
Maybe we could write the compiled kernel code into a global variable instead (and get rid of the python kernel)?

2021-03-09 21:40 UTC, bjoernenders commented on ptypy/accelerate/cuda_pycuda/array_utils.py
> +    def fill3D(self, A, B, offset=[0, 0, 0]):
Well but it doesn't make sense to compile all the other functions if you only need one either. A Kernel class only makes if the methods are somehow joined to form a greater something, like a workflow. Maybe we need to rip this class apart. Open for suggestions, but a per-function/method cache for compiled code seems appropriate.

2021-03-09 21:42 UTC, bjoernenders commented on ptypy/accelerate/cuda_pycuda/array_utils.py
> +    def fill3D(self, A, B, offset=[0, 0, 0]):
We could also use the "`__call__`" method of classes to make them appear like functions

2021-03-09 21:46 UTC, xcelerit-team commented on ptypy/accelerate/cuda_pycuda/array_utils.py
> +    def fill3D(self, A, B, offset=[0, 0, 0]):
I agree with that in general. The fill3D method however performs lazy compilation on first use and caches in the object. A strategy like this could be used globally (there are other kernel classes in ptypy where the same applies). Some kind of kernel cache. 

But I guess the question is if now is the right time to do such refactorings?

2021-03-09 21:58 UTC, bjoernenders commented on ptypy/accelerate/cuda_pycuda/array_utils.py
> +    def fill3D(self, A, B, offset=[0, 0, 0]):
the `dot` product and the reductions belong together as they depend on each, the `transpose` has nothing to do in there (it's even a different dtype here), but I didn't bother complaining last time. And that you attached these other unrelated methods is a choice and not "refactoring". However, in lieu of a strategy, we can just go ahead and make a class for each collection of codependent methods.

2021-03-09 22:16 UTC, xcelerit-team commented on ptypy/accelerate/cuda_pycuda/array_utils.py
> +    def fill3D(self, A, B, offset=[0, 0, 0]):
All the CUDA kernels are part of such kernel classes. I simply continued with that and chose what appeared to be the most suitable choice. I am open to suggestions and can move this into a kernel class with call operator for example. 

With “refactoring” I meant the rest of the GPU kernels to follow the same pattern.

2021-03-09 22:27 UTC, bjoernenders commented on ptypy/accelerate/cuda_pycuda/array_utils.py
> +    def fill3D(self, A, B, offset=[0, 0, 0]):
Oh ok, I read you wrong. No I don't mean to refactor all Kernel classes because some share data types or memory buffers and the individual methods/kernels don't really mean anything outside the class construct or the methods are codependent or called recursively.

For isolated functions (like most of those that are in base/array_utils) we should however strive to make them separate objects as much as possible. I'll make a suggestion here in this branch

2021-03-10 08:56 UTC, bjoernenders approved these changes

2021-03-10 10:34 UTC, daurer approved these changes

2021-03-10 10:35 UTC, merged