includes scratchmem size in dict key
ptycho/ptypy pull request #308
Opened 2021-03-18 21:15 UTC by bjoernenders

This is the fix to get rid of the MemAlloc and MemFree. The problem was that the `scratchmem` would be made new each time `max_abs2` was applied to differently sized array, which was the feature programmed. But if we alternate between two differently sized arrays, it makes a new scratch each time. Another possible workaround would have been to use a separate `max_abs2` "Kernel" for probe and object update respectively

2021-03-19 08:39 UTC, daurer approved these changes

2021-03-19 09:46 UTC, xcelerit-team requested changes
While this will work, it will re-compile the kernel for every new array size it finds. 

I was thinking that having a different map for the scratchmem might be a better approach. Or alternatively, only reallocate if the memory is too small (but not too big). A too big array for scratch memory doesn't hurt - only a part of it will be used. The data type of the memory would still need to be considered though.

2021-03-19 17:52 UTC, bjoernenders commented
@lotzej good point. But the codes we do this for are for massive repetitions on the same structures and not to really write a library to cover all cases so I can live with the recompilation penalty. This one was quick, easy and even saves some lines of code. But feel free to push an alternative at the end of the hackathon if there are some cycles left.

2021-03-24 10:49 UTC, daurer commented
Going to merge this, we can still look into alternative solutions if there is time left at the end of the hackathon.

2021-03-24 10:49 UTC, merged